version: '3'

services:
  ################################
  #   Setup angular container
  ################################
  mysmoothie-ng:
    build: .
    ports:
      - 8087:80
  ################################
  #   Setup nginx load balancer
  ################################
#  nginx:
#    image: nginx:1.13 # this will use the latest version of 1.13.x
#    ports:
#      - 80:80 # expose 80 on host and sent to 80 in container
#    depends_on:
#      - mysmoothie-ng
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
